# Generated by Django 4.0.3 on 2024-06-27 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0011_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
