# Generated by Django 4.0.3 on 2024-07-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0015_invoice_status_alter_category_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='order_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
