# Generated by Django 4.0.3 on 2024-07-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0016_invoice_order_type_invoice_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='product_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
