# Generated by Django 4.0.3 on 2024-07-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0017_invoice_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_code',
            field=models.IntegerField(default=0),
        ),
    ]
