# Generated by Django 4.0.3 on 2024-07-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0019_pipe_jbolt_baseplate_arm'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoleTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=255)),
                ('customer_code', models.CharField(max_length=100)),
                ('order_type', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=255)),
            ],
        ),
    ]
