# Generated by Django 4.0.3 on 2024-07-18 09:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0020_poletransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='poletransaction',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='poletransaction',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='poletransaction',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Completed'), ('3', 'Inactive')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='poletransaction',
            name='customer',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='poletransaction',
            name='customer_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poletransaction',
            name='order_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='poletransaction',
            name='product_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
