# Generated by Django 4.0.3 on 2024-07-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0021_poletransaction_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseplate',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='jbolt',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='pipe',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='poletransaction',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='poletransaction',
            name='arms',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='poletransaction',
            name='base_plate_hole_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poletransaction',
            name='base_plate_shape',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='poletransaction',
            name='base_plate_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poletransaction',
            name='base_plate_thickness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poletransaction',
            name='jbolt_bend',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poletransaction',
            name='jbolt_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poletransaction',
            name='jbolt_thread',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poletransaction',
            name='pipes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='poletransaction',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poletransaction',
            name='customer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='poletransaction',
            name='customer_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='poletransaction',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='poletransaction',
            name='order_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='poletransaction',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='poletransaction',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Completed'), ('3', 'Inactive')], default='1', max_length=255),
        ),
        migrations.DeleteModel(
            name='Arm',
        ),
        migrations.DeleteModel(
            name='BasePlate',
        ),
        migrations.DeleteModel(
            name='JBolt',
        ),
        migrations.DeleteModel(
            name='Pipe',
        ),
    ]
