# Generated by Django 4.0.3 on 2024-07-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0022_remove_baseplate_invoice_remove_jbolt_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.CharField(choices=[('conventional_light', 'Conventional Light'), ('solar_light', 'Solar Light'), ('wall_washer', 'Wall Washer'), ('flood_light', 'Flood Light'), ('fancy_lights', 'Fancy Lights')], max_length=250),
        ),
    ]
