# Generated by Django 4.0.3 on 2024-07-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0024_alter_invoice_customer_alter_invoice_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poletransaction',
            name='base_plate_hole_quantity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='poletransaction',
            name='base_plate_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='poletransaction',
            name='base_plate_thickness',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='poletransaction',
            name='jbolt_bend',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='poletransaction',
            name='jbolt_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='poletransaction',
            name='jbolt_thread',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
