# Generated by Django 4.0.3 on 2024-07-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0025_alter_poletransaction_base_plate_hole_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poletransaction',
            name='order_type',
            field=models.CharField(choices=[('galvanize_pole', 'Galvanize Pole'), ('simple_paint_pole', 'Simple Paint Pole'), ('fancy_street_pole', 'Fancy Street Pole'), ('dynamic_Pole', 'Dynamic Pole')], max_length=250),
        ),
    ]
