# Generated by Django 4.0.3 on 2024-07-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0027_alter_invoice_customer_code_alter_invoice_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poletransaction',
            name='arm_bend',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='poletransaction',
            name='arm_design',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='poletransaction',
            name='breaker_strips',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='poletransaction',
            name='cnc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='poletransaction',
            name='design',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='poletransaction',
            name='hinge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='poletransaction',
            name='holder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='poletransaction',
            name='iron_strips',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='poletransaction',
            name='melon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='poletransaction',
            name='nipple',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='poletransaction',
            name='paint',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='poletransaction',
            name='silver_base',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='poletransaction',
            name='order_type',
            field=models.CharField(choices=[('street_light_pole', 'Street Light Pole'), ('fancy_street_pole', 'Fancy Street Pole'), ('simple_paint_pole', 'Simple Paint Pole'), ('dynamic_Pole', 'Dynamic Pole')], max_length=250),
        ),
    ]
