# Generated by Django 4.0.3 on 2024-07-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0029_poletransaction_silver_melon'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='poletransaction',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
