# Generated by Django 4.0.3 on 2024-07-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0030_invoice_description_poletransaction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poletransaction',
            name='status',
            field=models.IntegerField(choices=[(1, 'Completed'), (2, 'Active'), (3, 'Inactive')]),
        ),
    ]
