# Generated by Django 4.0.3 on 2024-07-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0031_alter_poletransaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poletransaction',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Completed'), ('3', 'Inactive')], default='1', max_length=255),
        ),
    ]
