# Generated by Django 4.0.3 on 2024-10-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0032_alter_poletransaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='customer',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='type',
            field=models.CharField(choices=[('1', 'Stock-in'), ('2', 'Stock-Out')], default='1', max_length=2),
        ),
    ]
